package org.ei.opensrp.household.analytics;

/**
 * Created by Safwan on 5/3/2016.
 */
public enum Events {
    LOGIN,
    CHILD_ENROLLMENT, CHILD_FOLLOWUP, CHILD_REGISTER, CHILD_FRAGMENT, CHILD_DETAIL_ACTIVITY,
    WOMAN_ENROLLMENT, WOMAN_FOLLOWUP, WOMAN_REGISTER, WOMAN_FRAGMENT, WOMAN_DETAIL_ACTIVITY,
    STOCK_VACCINATION_POSITION,
    BARCODE
}
